[package]
name = "message_shared"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true



[dependencies]
# Internal crates

# External crates
iggy = {workspace = true}

[lints]
workspace = true